@token = {{login.response.body.token}}
@testUserFirstname = "Test"
@testUserLastname = "Testowy"
@testUserEmail = "test@example.com"
@testUserPassword = "TestingPassword123!" 

# @name login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": {{testUserEmail}},
    "password": {{testUserPassword}}
}

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "firstname": {{testUserFirstname}},
    "lastname": {{testUserLastname}},
    "email": {{testUserEmail}},
    "password": {{testUserPassword}}
}

###
GET http://localhost:8080/company/@me
Content-Type: application/json
Authorization: {{token}}

### 
POST http://localhost:8080/company/@me
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Test Company",
    "type": "Jednoosobowa działalność gospodarcza",
    "nip": "123456789",
    "regon": "123456789",
    "street": "Testowa",
    "address": "10 lok. 10",
    "zipcode": "15-345",
    "city": "Testowo",
    "country": "Polska",
    "registerDate": "2024-01-01",
    "vat": false
}